### ISSUE TITLE
Microjson accepts garbage after last delimiter

### ISSUE THREAD

**Issue by vrthra** [phensley/microjson#3]
For example, the following gets parsed

```
{}abc => {}
[]xxx => []
0abcd => 0
```

**Comment by phensley** [comment]
This is intentional. The parser was designed to read JSON values embedded inside configuration files. For example, you might have a file like this: 

```
[replicas]
hosts = ["host01", "host02"]
priority = [10, 20]
```

The outer parser would parse `<key> =` and hand off to the inner JSON parser to read the value. The outer parser would resume from that point forward.
